### ISSUE TITLE
rustfix should handle multi-span suggestions

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rustfix#141]
Here:

https://github.com/rust-lang-nursery/rustfix/blob/89217428c130b62c7ddaa0734eb4ebaa33673a86/src/lib.rs#L191-L198

This issue concerns the matter of a single suggestion that happens to replace multiple spans (functionality that is not used _often_, but which [does exist](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.multipart_suggestion)). This is not to be confused with multiple suggestions that happen to touch the same code, which (if I understand correctly while reading quickly) was what #140 was about.

I'm happy to work on this because I need it for rust-lang/rust#53013.

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/pull/56220

**Comment by pietroalbini** [comment]
Fixed by #155

**Comment by ehuss** [comment]
I think in a sense this is resolved by #195. There is still an outstanding consideration that there is no way to distinguish between a diagnostic that has multiple spans, and one that has multiple variants. I think that is tracked in https://github.com/rust-lang/rust/issues/53934.
