### ISSUE TITLE
Useless blank lines added when removing extern crate statements

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/rustfix#158]
Here is a diff created by running `cargo fix --edition-idioms` on a piece of code:

``` diff
diff --git a/src/main.rs b/src/main.rs
index 900f3d2..3c06c49 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,10 +1,10 @@
-extern crate futures;
-extern crate hyper;
-extern crate hyper_tls;
-extern crate serde;
+
+
+
+
```

The four blank lines it substituted for the `extern crate` statements it removed are useless and just create a bunch of odd looking space in the source code. It'd be better to just remove the lines without replacement.

**Comment by jimmycuadra** [comment]
If someone can point me to where this happens in rustc, I can submit a PR.

**Comment by oli-obk** [comment]
The span is inserted [here](https://github.com/rust-lang/rust/blob/289ad6e9922683807d455ca0020dc2a8f7bd1a7b/src/librustc_resolve/check_unused.rs#L148). It is originally taken from the `extern crate` item [here](https://github.com/rust-lang/rust/blob/4bb5d35659b6d8579007f49db09aa1d35782b834/src/librustc_resolve/build_reduced_graph.rs#L387). We'd probably just want to expand the span during the reporting though, so we could do it in https://github.com/rust-lang/rust/blob/4a45578bc58ff262864f72680cc02e83f5d2f5b3/src/librustc_typeck/check_unused.rs#L84

Note that if this is pursued, the code complexity of that lint is increased significantly. You need to take care of all kinds of things like

* if you remove the newline before the `extern crate`, you need to check that you are not in the first line of a file
* you need to actually check for newlines/spaces, ... and not just remove a character
* you need to consider the effect of macros

I think we should just leave this to rustfmt. In clippy we have generally opted to do such fixes only if it is absolutely trivial.

**Comment by jimmycuadra** [comment]
Is there a way to signal to end users that rustfix intends for rustfmt to be run immediately afterward? This isn't intuitive to me at all, hence coming here with this issue. It never occurred to me that I was just expected to run rustfmt to fix ugliness left behind by rustfix. Just seems like a less than stellar UX as it stands.

**Comment by jimmycuadra** [comment]
Just changing the UI of `cargo fix` might be a satisfactory approach. Maybe just adding something to the output of running it suggesting a subsequent rustfmt run, or at the least just part of rustfix's help text. Maybe even `cargo fix --fmt` that automatically shells out to rustfmt if the fix completed successfully.

**Comment by ehuss** [comment]
cc https://github.com/rust-lang/rust/issues/51176

**Comment by clarfonthey** [comment]
Wondering if there's been any progress on this issue since it's been reported, since it's still an issue. While I do think that a `fix --fmt` option would be nice, I think that removing the newline in all cases would be helpful, since there are definitely situations where you would like to run `cargo fix` without reformatting an entire file.

Perhaps the reformatting could be scoped to the parts that have been fixed, somehow? Maybe that's something that would have to be implemented on rustfmt's end. For example, one thing that could be useful is a `cargo fix` affecting imports could *just* run the import reformatting rules, reordering the imports at the upper level of the file while leaving all other items intact.

**Comment by ehuss** [comment]
Closing in preference to https://github.com/rust-lang/rust/issues/51176, since this would need to be fixed in the compiler.
