### ISSUE TITLE
Performance: Use SmallVec in rustfix

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rustfix#194]
I suggest using [`SmallVec`](https://docs.rs/smallvec/1.6.1/smallvec/struct.SmallVec.html) [(`smallvec` crate)](https://github.com/servo/rust-smallvec) instead of a regular Vec to improve performance, by having a SmallVec allocate primarily on the stack and the heap is secondary.

## Where this could be useful
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L28-L29
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L65-L66
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L72
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/replace.rs#L33-L34
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L107
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L131
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/lib.rs#L191
* https://github.com/rust-lang/rustfix/blob/ae9b64599c43a49a164ab8b4d0eb9947fd2ab117/src/replace.rs#L163

Of course, **it doesn't make sense to blindly replace** something like that, but you could analyze this with benchmarks to see where a SmallVec would make sense.

## Additional/useful resources
* [Reddit: Improving SmallVec's speed by 60% and why that shouldn't matter to you](https://www.reddit.com/r/rust/comments/8l8l7k/improving_smallvecs_speed_by_60_and_why_that/)
* [Benchmarking with criterion](https://crates.io/crates/criterion)
* [Profiling with perf](https://perf.wiki.kernel.org/index.php/Main_Page)

**Comment by ehuss** [comment]
I'm going to close as I don't think performance has been much of a concern.
