### ISSUE TITLE
`cargo fix` doesn't work for errors

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustfix#208]
I tried this code:
```rust
fn f(x: &str) {}
fn main() {
    f(String::new())
}
```
I got this error:
```
error[E0308]: mismatched types
 --> src/main.rs:3:7
  |
3 |     f(String::new())
  |       ^^^^^^^^^^^^^
  |       |
  |       expected `&str`, found struct `String`
  |       help: consider borrowing here: `&String::new()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```
I ran `cargo fix`, but it had no effect. It would be nice if cargo fix worked for errors and not just warnings - I have a lot of autofixable errors like this and I'd like to not have to fix them manually one by one.

**Comment by ehuss** [comment]
The `--broken-code` flag should allow that.  Does that work for you?

```       
 --broken-code               Fix code even if it already has compiler errors
```

**Comment by jyn514** [comment]
Ah, there it is! I was looking for `--fix-broken` and when I didn't find it, I thought I'd imagined the flag :laughing:

Thanks!
