### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rustfix#211]
Could you please publish a new release of `rustfix`?

An attempt to add functionality to Clippy is running into the bug fixed by #199 (see https://github.com/rust-lang/rust-clippy/pull/8844#issuecomment-1133676340).

Would it be possible to publish a version with this fix?

Thank you.

**Comment by Manishearth** [comment]
Happy to do so if someone makes a PR with a version bump

**Comment by Manishearth** [comment]
Done, thanks!

**Comment by smoelius** [comment]
Thank you!
