### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by 3tilley** [rust-lang/rustfix#221]
Hello,

Could the README be improved to help someone trying to understand the state of this repo? My understanding is that it's not mothballed, but the relevant functionality for cargo now lives [here](https://github.com/rust-lang/cargo/blob/6fa6fdc7606cfa664f9bee2fb33ee2ed904f4e88/src/cargo/ops/fix.rs). Is that correct?

If so what would you imagine someone using this repo for, will it ever have changes backported to it?

If you're able to give a brief summary I'm happy to make the PR to improve the landing page!

**Comment by Manishearth** [comment]
Cargo uses this crate as a library, there's nothing to backport. This crate is mostly "done" unless cargo wants more from it, which is generally not going to be likely. We're not opposed to adding new stuff but we'd probably weigh that against the burden of maintaining it.

**Comment by 3tilley** [comment]
Addressed in #222, thanks!
