### ISSUE TITLE
"Edition mode"

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rustfix#62]
Would be nice to have a mode where:

 - It only applies edition lints
 - It does this automatically, but prompts for approximate suggestions
 - You can optionally ask it to apply idiom lints too

We can hardcode the list of edition lints and idiom lints

**Comment by Manishearth** [comment]
It occurs to me that for approximate suggestions we should spit them out _after_ we've fixed everything else, so that if the user makes manual changes it's nbd. We should nail down a workflow here.

**Comment by ehuss** [comment]
I'm going to close as I believe this is mostly resolved by the `--edition` flag.
